# Configuration file for access via CloudCannon interface
global:
  site_url: 'https://www.marinavip.com.br'
  title: 'Marina VIP - Marina em Balneário Camboriú'
  tel: '+55 (47) 9 9619-0008'
  email: 'marinavip@marinavip.com.br'
  social:
    - icon: "Facebook"
      url: 'https://facebook.com'
    - icon: "Instagram"
      url: 'https://instagram.com'   
    - icon: "Messenger"
      url: 'https://messenger.com'
    - icon: "WhatsApp"
      url: 'https://wa.me/+5547992041363'
  preview_image:  
##### Fonts #####
fonts:
  google_fonts_embed_code_block: '<link href="https://fonts.googleapis.com/css2?family=Bitter:ital,wght@0,100;0,300;0,400;0,600;1,100;1,300;1,400;1,600&family=Questrial&display=swap" rel="stylesheet">' 
  body_font_family: "'Questrial', serif;"
  heading_font_family: "'Questrial', sans-serif;"

##### Site main colors #####
colors:
  dark_color: '#363636'
  light_color: 'whitesmoke'
  accent_color: '#003453'

##### Navigation menus and submenus #####
navigation:
  menus:
    - name: Início
      url: /
      dropdown: false
      submenus:
        - name:
          url:
    - name: Estrutura
      url: 
      dropdown: true
      submenus:
        - name: Restaurante
          url: 
        - name: Member's Club
          url: 
    - name: Serviços
      url: /servicos
      dropdown: false
      submenus:
        - name: Manutenção
          url: 
        - name: Charter Management
          url:  
    - name: Aluguel
      url:
      dropdown: false
      submenus:
        - name: Manutenção
          url: 
        - name: Charter Management
          url:
    - name: Passeios
      url: /
      dropdown: True
      submenus:
        - name: Balneário Camboriú
          url: /passeios/balneario-camboriu
    - name: Contato
      url: /contato
      dropdown: false
      submenus:
        - name:
          url:  
seo:
  site_description_text: Here's the site description text
  keywords: ['vela oceânica', 'cursos de vela oceânica', 'passeios de barco em balneário camboriu']